# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Rodrigo Díez Villamuera
email: rodrigo@rodrigodiez.io
description: > # this means to ignore newlines until "baseurl:"
  I optimize companies' revenue / cost ratio via high quality software,
  agile methodologies and some good ideas. I run miles too
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://yourdomain.com" # the base hostname & protocol for your site

# Author settings
author:
    name: Rodrigo Díez Villamuera
    bio: >
        I am an agile web developer. I help business' to increase their revenue / cost ratio via high quality software, iterative improvement and some good ideas. I also run miles and [write about it](http://rodrigodiez.github.io)
    location: London, UK
twitter_username: rodrigodiez_pro
github_username:  rodrigodiez
linkedin_username:  rodrigodiezvillamuera

# Build settings
markdown: kramdown

# Dir structure settings
exclude: [Gemfile, Gemfile.lock, bin, bower.json]
