baseURL: https://rodrigodiez.io/
languageCode: en-gb
title: "Rodrigo Diez"
theme: github.com/adityatelange/hugo-PaperMod

outputs:
  home:
    - HTML
    - RSS
    - JSON # for search

params:
    author: "Rodrigo Diez"
    keywords: ["Rodrigo Diez", "software engineer", "solutions architect", "contractor", "go", "golang", "gRPC", "kafka", "kubernetes", "k8s", "distributed systems"]
    description: "Software Engineer and Solutions Architect with a strong entrepreneurial and leadership background bringing 15 years of experience in multiple problem and solution spaces across industries such as Defence, Music and Education. Proficient with Cloud Native stacks, specially those involving Go, gRPC, Kafka and Kubernetes, as well as experienced in the development of Distributed Services with strict Availability and Latency requirements."
    profileMode:
        enabled: true
        # title: "Rodrigo Diez" # optional default will be site title
        subtitle: Software Engineer / Solutions Architect / For hire
        imageUrl: "/avatar.jpg" # optional
        imageTitle: "Rodrigo Diez" # optional
        # imageWidth: 120 # custom size
        # imageHeight: 120 # custom size
        buttons:
            - name: Download resume
              url: "/rodrigo-diez-resume.pdf"
    socialIcons: # optional
        - name: "email"
          url: "mailto:rodrigo@rodrigodiez.io"
        - name: "github"
          url: "https://github.com/rodrigodiez"
        - name: "linkedin"
          url: "https://www.linkedin.com/in/rodrigodiezvillamuera/"

# menu:
#   main:
#     - identifier: blog
#       name: Blog
#       url: /blog/
#     - identifier: search
#       name: Search
#       url: /search/

module:
  imports:
  - path: github.com/adityatelange/hugo-PaperMod
