# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Rodrigo Díez Villamuera
email: rodrigo@rodrigodiez.io
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://yourdomain.com" # the base hostname & protocol for your site

# Author settings
author:
    name: Rodrigo Díez Villamuera
    bio: >
        Internet builder, long distance runner. Spaniard
twitter_username: rodrigodiez_pro
github_username:  rodrigodiez
linkedin_username:  rodrigodiezvillamuera

# Build settings
markdown: kramdown

# Dir structure settings
source: src
destination: dist
exclude: [Gemfile, Gemfile.lock]
